# Generated by Django 4.1.2 on 2022-10-06 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('CandidateID', models.IntegerField(primary_key=True, serialize=False)),
                ('EnrollmentNumber', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('EMail', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('Branch', models.CharField(max_length=255)),
                ('Year', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=255)),
                ('CG', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment_Season',
            fields=[
                ('SeasonID', models.IntegerField(primary_key=True, serialize=False)),
                ('Year', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('RoundID', models.IntegerField(primary_key=True, serialize=False)),
                ('SeasonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.recruitment_season')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnrollmentNumber', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Branch', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=255)),
                ('Year', models.CharField(max_length=255)),
                ('EMail', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=255)),
                ('UserName', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('DOB', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('SectionID', models.IntegerField(primary_key=True, serialize=False)),
                ('SectionName', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=255)),
                ('RoundID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.round')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('QuestionID', models.IntegerField(primary_key=True, serialize=False)),
                ('QuestionStatement', models.CharField(max_length=255)),
                ('AnswerType', models.CharField(max_length=255)),
                ('SectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.section')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluatorPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeSlot', models.CharField(max_length=255)),
                ('EvaluationStatus', models.CharField(max_length=255)),
                ('RoundStatus', models.CharField(max_length=255)),
                ('CurrentStatus', models.CharField(max_length=255)),
                ('CandidateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.candidate')),
                ('RoundID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.round')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CandidateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.candidate')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='RoundID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.round'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='SeasonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.recruitment_season'),
        ),
    ]
