# Generated by Django 4.1.2 on 2022-10-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_round',
            name='CurrentStatus',
        ),
    ]
